export enum EntityNames {
  USER = 'user',
  USER_ADDRESS = 'user_address',
  USER_BASKET = 'user_basket',
  CATEGORY = 'category',
  SUPPLIER = 'supplier',
  USER_OTP = 'user_otp',
  SUPPLIER_OTP = 'supplier_otp',
  MENU = 'menu',
  MENU_TYPE = 'menu_type',
  MENU_FEEDBACK = 'menu_feedback',
  DISCOUNT = 'discount',
  ORDER = 'order',
  ORDER_ITEM = 'order_item',
  PAYMENT = 'payment',
}
