export enum SupplierStatus {
  REGISTERED = 'REGISTERED',
  SUPPLEMENTARY_INFORMATION = 'SUPPLEMENTARY_INFORMATION',
  UPLOADED_DOCUMENTS = 'UPLOADED_DOCUMENTS',
  CONTRACT = 'CONTRACT',
  ACCEPTED = 'ACCEPTED',
}
